/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#undef  ENABLE_USB
#define ENABLE_SDIO 1
#define RSI_CONFIG_LINUX 1
#undef  RSI_CONFIG_ANDROID
#undef  ONEBOX_CONFIG_NL80211
#undef  HOSTAPD_SUPPORT
#define ENABLE_WLAN 1
#undef  ENABLE_BT
#undef  ENABLE_ZIGB
